### ISSUE TITLE
Improve performance?

### ISSUE THREAD

**Issue by FezVrasta** [iRoachie/react-native-material-tabs#11]
I notice quite some lag with this component (when it animates), is there any chance to get some performance boost somehow?

**Comment by iRoachie** [comment]
Hey @FezVrasta which platform did you experience this on? Also what’s our react-native version?

**Comment by FezVrasta** [comment]
I used the latest Expo react-native fork, I experienced lag especially on iPhone 6, but also on Android.

**Comment by iRoachie** [comment]
I'm not experiencing this behavior, see a video I just made https://youtu.be/fDU9dOqRUpw. This is on iPhone 6

**Comment by FezVrasta** [comment]
I guess it has to do with the amount of work done while the tab is changing. Are you using native driven animations?

**Comment by iRoachie** [comment]
Just updated it to! https://github.com/iRoachie/react-native-material-tabs/pull/12

**Comment by FezVrasta** [comment]
Great thanks!

**Comment by iRoachie** [comment]
Live! v3.1.0
