### ISSUE TITLE
tabs will not resize when one is removed or added

### ISSUE THREAD

**Issue by dlombardi** [iRoachie/react-native-material-tabs#13]
As a developer who wants to add or remove tabs dynamically the tabs will not resize themselves when a tab is removed or added resulting in an unresponsive experience.

**Comment by iRoachie** [comment]
Alright should be an easy fix, just need to add if `items` changes in https://github.com/iRoachie/react-native-material-tabs/blob/master/src/components/MaterialTabs.js#L54

**Comment by iRoachie** [comment]
Fixed in https://github.com/iRoachie/react-native-material-tabs/pull/14/commits/5458ac0b7331ee2487e75b9da5fcf02013b0d7dc. Will be live shortly

**Comment by iRoachie** [comment]
Live in v3.1.1 🎉
