### ISSUE TITLE
render view for each tab

### ISSUE THREAD

**Issue by aminvb12** [iRoachie/react-native-material-tabs#18]
Hey there
How Can I render a simple view for each of the tabs?

**Comment by iRoachie** [comment]
Hey @aminvb12 you can use a state variable to conditionally show different views.

Here's an example https://snack.expo.io/@roach_iam/multiple-pages-with-materialtabs

**Comment by jeffreymendez1993** [comment]
You could add a renderView to the component but that will add a extra layer that is really not intended for. Also have you tested this on android @iRoachie thoroughly?  Not sure if its the package but it doesnt render fully until a half second on initial load.

**Comment by iRoachie** [comment]
Yea @jeffreymendez1993 I haven't come across that problem with rendering on android. Remember that rendering and it's time is dependent on the all the components you have on the screen. So you may want to check other components you have in your tree.
