### ISSUE TITLE
disable fontScaling 

### ISSUE THREAD

**Issue by jeffreymendez1993** [iRoachie/react-native-material-tabs#20]
Can you add the allowFontScaling prop so we can enable or disable. If there are 3 tabs at size 15px for each tab and if you have your font Scaled to Max on iOS it breaks the layout/view.

**Comment by iRoachie** [comment]
Sure thing.

**Comment by iRoachie** [comment]
Added in https://github.com/iRoachie/react-native-material-tabs/pull/22/commits/8f7ebd70ee1ac840d029c84476885b29b98464ab. Will be available next release

**Comment by iRoachie** [comment]
Released! https://github.com/iRoachie/react-native-material-tabs/releases/tag/v3.4.0
