### ISSUE TITLE
componentWillUpdate is deprecated please use componentDidUpdate

### ISSUE THREAD

**Issue by jeffreymendez1993** [iRoachie/react-native-material-tabs#21]
for newer versions of RN this package will need to be updated at some point.
<img width="305" alt="screen shot 2018-03-30 at 9 48 07 am" src="https://user-images.githubusercontent.com/8095978/38139901-76bcf1fe-33ff-11e8-988f-a6306163654d.png">

**Comment by iRoachie** [comment]
I'm not sure how to go about upgrading this as yet. I can use `getDerivedStateFromProps` but I don't want to break existing functionality since it's only available in react 16.3.

**Comment by iRoachie** [comment]
For now I'll move the login to `componentDidUpdate`

**Comment by iRoachie** [comment]
Fixed in https://github.com/iRoachie/react-native-material-tabs/pull/22/commits/30250516515f00f76650c389a0aa75423b0b94ac will be available next release

**Comment by iRoachie** [comment]
Released! https://github.com/iRoachie/react-native-material-tabs/releases/tag/v3.4.0
