### ISSUE TITLE
allow adjustment of Bar position to allow thin borders to render above

### ISSUE THREAD

**Issue by jeffreymendez1993** [iRoachie/react-native-material-tabs#23]
I would like the bar to be slightly positioned lower since I wrapped the component in a view to add a thing border bottom border.

**Comment by iRoachie** [comment]
Hey @jeffreymendez1993, not sure I'm understanding you clearly. What is your intended finished intention and what would need to change to make that happen.

**Comment by jeffreymendez1993** [comment]
Actually its fine. Before my layout I wanted to apply a thing border underneath the tab bar since I was using it at the top of my view. With a thin border applied to the view wrapping the tab the bar line would be directly above the border applied to the container. It would have been nice to have control of its position or the ability to add barStyle={top:1} to slightly bring it down to rest with the border in one unified line. Also theres a slight flicker on first loading the view with 3 elements and data fetching occuring.

**Comment by iRoachie** [comment]
So something like a container style that surrounds the bar?

**Comment by iRoachie** [comment]
You may want to make a separate issue for talking about the flickering, If you can add images/videos/code that would help as well

**Comment by iRoachie** [comment]
Closing as inactive
