### ISSUE TITLE
disable text to upperCase.

### ISSUE THREAD

**Issue by jeffreymendez1993** [iRoachie/react-native-material-tabs#24]
Currently all text is uppercased would be nice to have this as a option.

**Comment by iRoachie** [comment]
Cool idea! Will add this in

**Comment by iRoachie** [comment]
Added in https://github.com/iRoachie/react-native-material-tabs/commit/ba9f8c77592a36d2d90cab33bf5ab6ecd156463c. Will be available next release

**Comment by iRoachie** [comment]
Released in [`v3.5.0`](https://github.com/iRoachie/react-native-material-tabs/releases/tag/v3.5.0)
