### ISSUE TITLE
Initial tab is not displayed in screen

### ISSUE THREAD

**Issue by xempie** [iRoachie/react-native-material-tabs#25]
Is that possible to display the initial tab on screen when the number of tabs are more than fitting in to screen width?
I have 10 tabs and if the initial tab index is greater than 2 it doesn't bring it to the screen and need to scroll to see the selected one.

**Comment by iRoachie** [comment]
Ohh sounds like an interesting use case, so on mount the component should scroll to the active tab if it's off the screen your saying?

**Comment by iRoachie** [comment]
Alright! Seems like it should be simple to add in. I'll check it over the weekend

**Comment by iRoachie** [comment]
So guys I just tested this, and it should already be doing this behavior. Here's a snack showing this https://snack.expo.io/SyrbX253G. The tab bar scroll to the tab regardless if it's on the screen or not.

**Comment by xempie** [comment]
Actually it does not work for me. I'm texting on physical Android device and SafeAreaView is only for iOs, so when I remove SafeAreaView wrap it's still the same.

**Comment by iRoachie** [comment]
Ahh yea, seems to be only happening on android. I think I have a fix that might address that

**Comment by iRoachie** [comment]
@xempie Can you try using the `next` branch and see if it works for you?

```bash
npm install --save https://github.com/iRoachie/react-native-material-tabs.git\#next
```

**Comment by iRoachie** [comment]
Closing as inactive
