### ISSUE TITLE
Active Tab Text Style

### ISSUE THREAD

**Issue by ianlaidlaw** [iRoachie/react-native-material-tabs#29]
Was wondering if this was something that has been considered - passing in a custom style similar to how you can pass in a different colour for the activeTextColor. 

Right now all text styles are the same, but I would like the active tab to be bolded, as an example.

**Comment by iRoachie** [comment]
This sounds like a great idea!

**Comment by iRoachie** [comment]
Released in [v3.6.0](https://github.com/iRoachie/react-native-material-tabs/releases/tag/v3.6.0)
