### ISSUE TITLE
Scrollable tabs

### ISSUE THREAD

**Issue by cyaxares** [iRoachie/react-native-material-tabs#3]
The number of my Tabs is received  from Server (I mean It's variable) and It could be 10 Tabs or more in the same place, so that my categories are shown badly. How can I remove this amount that's divided by Tabs' number and also have a horizontal scroll to show my Tabs in their own size(my Tabs move by pushing to left or right)??
![as](https://cloud.githubusercontent.com/assets/9538639/24840892/e6ec219c-1d8b-11e7-9318-bc187880f3ce.png)

Is there any way to show Tabs' content from Top to the Bottom and under each other(I mean when u reach at the last content of one Tab, if u keep on pushing to the Top the contents of next tab is shown )?
Thank u for previous update and for everything  :)

**Comment by iRoachie** [comment]
Would having scrollable tabs across solve your problem?

**Comment by cyaxares** [comment]
yes. I  wanna remove the width's limit in Tabs (If there is 10 Tabs for e.g fifth of them are shown and others are shown by scrolling ). 
I also want it to hide first Tab from right  whenever I reached in a hidden Tab from left  by scrolling.
If  there is a way to change Tabs by pushing contents into the Top screen as I said, I'll be Thankful.

**Comment by iRoachie** [comment]
Alright sounds good, I think it's something that would be great to have. Feel free to send a pr

**Comment by cyaxares** [comment]
I'll be Thankful If u do it. I'm doing other parts of my project & I'll be waiting for next update. How much time it takes to do for u?

**Comment by iRoachie** [comment]
@cyaxares I'll see if I can do it a night this week

**Comment by cyaxares** [comment]
Hi, Did u make progress by now?
What's your idea about time it takes?

Thanks

**Comment by iRoachie** [comment]
@cyaxares Implemented! I'll push new version to npm soon
