### ISSUE TITLE
_this3.props.onChange is not a function

### ISSUE THREAD

**Issue by ithustle** [iRoachie/react-native-material-tabs#44]
I'm facing this error. 

My code:

```
<MaterialTabs
                items={
                    [
                        <FontAwesome name={"home"} size={24} style={[styles.icons, { color: "#fff" }]}/>, 
                        <Icon name={"search"} size={24} style={[styles.icons, { color: "#fff" }]}/>, 
                        <Icon name={"genero"} size={24} style={[styles.icons, { color: "#fff" }]}/>, 
                        <Icon name={"minhas_musicas"} size={24} style={[styles.icons, { color: "#fff" }]}/>
                    ]
                }
                selectedIndex={this.state.selectedTab}
                onChange={this.setTab}
                barColor="#222"
                indicatorColor="#ff2a00"
                activeTextColor="#fff"
            />
```

Any help?

**Comment by iRoachie** [comment]
Did you define the `setTab` function you have there?

**Comment by ithustle** [comment]
Yep. Something like: 

`
setTab = selectedTab => {
            console.log(selectedTab)
            this.setState({ selectedTab: 1 });
        }
`

**Comment by iRoachie** [comment]
Can you show the whole example or recreate part of it on https://snack.expo.io that reproduces this?

**Comment by ithustle** [comment]
Oh damn! Shame on me... I've put `setTab` function inside `render()` ... My bad. Sorry. It's solved. Thanks for your time :)

**Comment by iRoachie** [comment]
All good! Glad you got it sorted out

**Comment by ithustle** [comment]
One more thing: 

How can I avoid `Warning: Encountered two children with the same key, `null`. Keys should be unique so that components maintain their identity across updates. Non-unique keys may cause children to be duplicated and/or omitted — the behavior is unsupported and could change in a future version.` using `components` on `items` instead `text`?

**Comment by iRoachie** [comment]
In your items array, just add a key on to the items.

```<FontAwesome name={"home"} size={24} style={[styles.icons, { color: "#fff" }]} key="home" />```

**Comment by ithustle** [comment]
You rock!
