### ISSUE TITLE
RTL Support 

### ISSUE THREAD

**Issue by saharjedidi** [iRoachie/react-native-material-tabs#49]
the  animation for selecting in RTL doesn't support 
the indicator doesn't show in the second and the third tabs 
this is the first tab 
<img width="428" alt="Screen Shot 2019-04-16 at 10 53 52 AM" src="https://user-images.githubusercontent.com/45098179/56200106-0af77200-6036-11e9-8bb8-0d28d5ee01e4.png">

but when I choose the next one the indicator doesn't show
<img width="428" alt="Screen Shot 2019-04-16 at 10 54 05 AM" src="https://user-images.githubusercontent.com/45098179/56200148-1f3b6f00-6036-11e9-8a4f-d499e5bf7aab.png">

**Comment by mohmdalfaha** [comment]
@saharjedidi Hi !! Did you find solution for this ??

**Comment by iRoachie** [comment]
How would I replicate this? 

I changed my simulator language to Arabic then ran the example. Everything seems to work as normal.

**Comment by mohmdalfaha** [comment]
The issue exists only on android devices cuz iOS by default is not set to RTL even if you change the language to Arabic. The underline is not sticky with the tab while moving between tabs. I notice that the direction of the moving tabs is only from left to right. I will share an some screenshot with you soon.

**Comment by mohmdalfaha** [comment]
I am really sorry for the delay, I ended up making my own tabs component that is more simplified and easy to reason about. I extremely appreciate your work 

below is my component:-
https://snack.expo.io/@mohmdalfaha/faha---scrollabletoptabbar---enjoy

The support for RTL is really poor and we can only expect individual workarounds. I would invest in this once I am done with some projects.

Thanks anyway,,

**Comment by iRoachie** [comment]
Just released a new version v4.1.0 that supports RTL. Thanks for the tip about testing RTL on android
