### ISSUE TITLE
RTL Support

### ISSUE THREAD

**Issue by cyaxaresi** [iRoachie/react-native-material-tabs#5]
Hello iRoachie
new update is so much better than previous,Thanks.
There is 2 issue that annoys.
1.selecting Tabs just by touching the Text of it. It's better to be selected also by touching the Tabs. cause some Tab'texts are too short to be selected easily.
2.If phone's language is RTL, animation for selecting that is used doesn't support.

**Comment by iRoachie** [comment]
Hey @cyaxaresi touching the text doesn't change the tab, there's a button underneath that spans the whole width of the tab.

I'll look into RTL support, I've never used it before.

**Comment by iRoachie** [comment]
Hey @cyaxaresi I just ran a demo using RTL and it works fine. What problems are you having? Could you record a video ?

**Comment by cyaxaresi** [comment]
As you can see in this video, for LTR language, when I click on second Tab, the first Tab moves to left and the third Tab is shown, so It's exactly what we expect. and for RTL language, It has to be unlike previous and move to left instead of right. But It moves to left and this is the problem and when I click on third Tab ,It is completely hidden from screen.
![emul](https://cloud.githubusercontent.com/assets/15978909/26024958/9e66e4d0-37f2-11e7-8871-640b990c35af.gif)

**Comment by iRoachie** [comment]
I tried making a test RTL project by using the `forceRTL` from I8lnManager but it worked fine for me.

Can you setup a basic github repo that I could run tests on?

**Comment by cyaxaresi** [comment]
Use this code for RTL , and change device's language into  Arabic(العربیه) or Persian(فارسی) 
So It will be RTL, and u will see the problem
     <MaterialTabs
                        items={['اول', 'دوم', 'سوم', 'چهارم', 'پنجم']}
                        selectedIndex={this.state.selectedTab}
                        onChange={this.setTab.bind(this)}
                        barColor="#1fbcd2"
                        indicatorColor="#fffe94"
                        scrollable={true}
                        activeTextColor="white"
                      />

**Comment by iRoachie** [comment]
@cyaxaresi It works fine for me, here's a video I recorded with the language set to Arabic
https://monosnap.com/file/F8HgUSwCJOcDL2x1l07M6o9vzPIDRL

**Comment by iRoachie** [comment]
Hey @cyaxaresi I haven't heard back from you. Will close this in the mean. When you come back you can reopen

**Comment by Shabnam-Veranloo** [comment]
@cyaxaresi  i have same problem.. do have any solution?

**Comment by iRoachie** [comment]
@Shabnam-Veranloo I wasn't really sure how it was supposed to work in RTL so I didn't know how best to create a solution
