### ISSUE TITLE
MaterialTabs is not showing on my screen

### ISSUE THREAD

**Issue by Supportlik** [iRoachie/react-native-material-tabs#50]
Hi,

if I use this component there is nothing my screen. When i put two text components before and after MaterialTabs the text components are just next to each other without tabs in between.

On ExpoSnack the Component is working, but on my own machine it is not.

Tested with and without expo eject.
Expo Version on DevMachine: 2.15.4
Tried Linux and Windows

Greetings
Michael

**Comment by iRoachie** [comment]
Can you create an example on https://snack.expo.io that reproduces this?

**Comment by Supportlik** [comment]
Of course: https://snack.expo.io/@supportlik/materialtabsnotworking

**Comment by iRoachie** [comment]
I'm not sure how I can help you then. The snack works and it should work the same way locally. This lib is fully javascript and has no native dependencies, so it should display the same without expo

**Comment by Supportlik** [comment]
It is resolved. Somehow a caching issue. On my private machine the code is running as it is.
