### ISSUE TITLE
Option to disable "bouncyness"

### ISSUE THREAD

**Issue by Strayer** [iRoachie/react-native-material-tabs#7]
Hi,

first of all, thanks for the library! I wondered about the bouncing tab indicator when switching tabs… I never saw material tabs like that.

According to the design guidelines the animation shouldn't bounce. It would be great if there would be an option (for backwards-compatibility) to disable the bouncy behaviour to adhere the specs.

https://material.io/guidelines/components/tabs.html#tabs-specs

material.io animation specs:
![](https://thumbs.gfycat.com/VillainousPaleCassowary-size_restricted.gif)

react-native-material-tabs for comparison:
![](https://camo.githubusercontent.com/eb1d092646a63d05fad626008a6d8d8f22e550e0/687474703a2f2f692e696d6775722e636f6d2f4759754d674d422e676966)

**Comment by iRoachie** [comment]
@Strayer Oooo that's true. Initially I did it to give the UI some life. It's a good suggestion, I'm happy to accept a PR that does this.

**Comment by iRoachie** [comment]
@Strayer Corrected in https://github.com/iRoachie/react-native-material-tabs/commit/19e4fa6ce3d213ae706bb84621afb2b6a20f9e03

**Comment by iRoachie** [comment]
Thanks!
